config/routes.rb
Rails.application.routes.draw do
  root :to => "games#index"
  
  resources :games

  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_filter :add_allow_credentials_headers

def add_allow_credentials_headers
  # https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#section_5
  #
  # Because we want our front-end to send cookies to allow the API to be authenticated
  # (using 'withCredentials' in the XMLHttpRequest), we need to add some headers so
  # the browser will not reject the response
  response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'
  response.headers['Access-Control-Allow-Credentials'] = 'true'
end

def options
  head :status => 200, :'Access-Control-Allow-Headers' => 'accept, content-type'
end

	def index
		@games = Game.all

		respond_to do |format|
			format.html # index.html.erb
			format.any(:xml, :json) { render request.format.to_sym => @games }
		end
	end

  def new
	@game = Game.new
	end

	def create
		@game = Game.new(params[:game].permit!)

		if @game.save
			redirect_to @game
		else
			render 'new'
		end
	end

	def show
		@game = Game.find(params[:id])
		respond_to do |format|
			format.html # index.html.erb
			format.any(:xml, :json) { render request.format.to_sym => @game }
		end
	end


	def game_params
		params.require(:game).permit!
	end
	private :game_params

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])

	  if @game.update(params[:game].permit!)
		redirect_to @game
	  else
		render 'edit'
	  end
	end

	def destroy
	  @game = Game.find(params[:id])
	  @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :console %><br />
    <%= f.text_field :console %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
	<%= f.select :year, (1970..Time.now.year).to_a.reverse %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing Games</h1>

<script type="text/javascript">

mixpanel.identify('3')
mixpanel.people.set({
  "details": "third person",
  "account": "Nick's Account",
  "name": "Gerlando Piro"
})

mixpanel.track("Index Page", {
  "account": "Nick's Account/Second account"
});

/*mixpanel.track('page viewed', {
    'page name' : document.title,
    'url' : window.location.pathname
}); */

</script>

<h1>
  This is the branched app
</h1>

app/views/games/new.html.erb
<script type="text/javascript">

mixpanel.track("No identify on New", {
    "account": "Nick's Account"
});
</script>

<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<script type="text/javascript">

mixpanel.identify('2')
mixpanel.track("Video played", {
    "Video length": 213,
    "id": "hY7gQr0",
    "account": "Nick's Account"
});
</script>

<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @game.title %>
</p>

<p>
  <b>Console:</b>
  <%= @game.console %>
</p>

<p>
  <b>Year:</b>
  <%= @game.year %>
</p>

<p>
  <b>Description:</b>
  <%= @game.description %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome Index</h1>

<script type="text/javascript">
mixpanel.track("Landing Page");
</script>